// Each post's body is a list of content blocks so the [slug] page can render
// any post generically without needing custom JSX per article.
// Block types: h2, h3, p, ul (ul.items is an array of strings)

export const posts = [
  {
    slug: "12-month-study-plan",
    title: "How to Build a 12-Month UPSC Study Plan That Actually Survives Contact With Reality",
    description: "A realistic, stage-by-stage approach to planning a 12-month UPSC preparation calendar.",
    category: "Strategy",
    readTime: "8 min read",
    body: [
      { type: "p", text: "Most study plans fail in week three. Here's how to build one that bends without breaking." },
      { type: "h2", text: "1. Split the year into three real phases, not twelve equal months" },
      { type: "p", text: "Instead of a flat 12-month grid, divide your year into a Foundation phase, a Prelims-focused phase, and a Mains-focused phase, each with its own priorities." },
      { type: "h2", text: "2. Build revision into the plan from day one" },
      { type: "p", text: "Schedule a short revision block for every topic roughly three weeks after you first study it — this single habit does more for retention than almost anything else." },
      { type: "h2", text: "3. Leave one buffer day every week" },
      { type: "p", text: "A plan with zero slack breaks the first time you fall sick. One unscheduled day a week lets you absorb the unexpected without the whole plan collapsing." },
      { type: "h2", text: "4. Track completion, not just hours" },
      { type: "p", text: "Two hours of focused answer writing beats six hours of passive reading. Track topics completed and tests attempted instead, and review that weekly with your coach." },
      { type: "h2", text: "5. Review and rebuild the plan monthly" },
      { type: "p", text: "Your first plan is a draft, not a contract. Sit with your coach once a month and rebuild the next month's plan around what's actually working." },
      { type: "h3", text: "A simple way to start" },
      { type: "p", text: "Block out your three phases, mark your revision cycles, add your weekly buffer day, and commit to reviewing it in four weeks." },
    ],
    sidebarCta: { title: "Want a plan built for you?", body: "A coach can build your actual plan around your job, background subjects and timeline.", href: "/contact#counselling", label: "Book Free Counselling" },
  },
  {
    slug: "answer-writing-framework",
    title: "The 3-Part Answer Writing Framework Toppers Actually Use",
    description: "A simple, repeatable structure for UPSC Mains answers that keeps every answer clear under time pressure.",
    category: "Mains",
    readTime: "6 min read",
    body: [
      { type: "p", text: "Ask any Mains topper how they write under time pressure, and you'll rarely hear \"I just write what I know.\" What you'll hear is some version of a structure — a repeatable shape they pour any topic into." },
      { type: "h2", text: "1. The introduction: define, don't repeat" },
      { type: "p", text: "A weak introduction just restates the question. A strong one defines the key term or sets the context in one or two lines." },
      { type: "h2", text: "2. The body: structure before content" },
      { type: "p", text: "This is where most marks are won or lost. Toppers decide the structure before they write a single sentence." },
      { type: "ul", items: [
        "Group your points under 2–4 clear headings or dimensions",
        "Use short paragraphs or bullet points rather than long, winding sentences",
        "Bring in a fact or example wherever it's genuinely relevant",
      ] },
      { type: "h2", text: "3. The conclusion: forward-looking, not repetitive" },
      { type: "p", text: "Don't summarise what you just said. End with a way forward, a balanced judgement, or a link to a larger principle." },
      { type: "h3", text: "Practising the framework" },
      { type: "p", text: "The framework takes five minutes to learn. Making it automatic under exam pressure takes weeks of coach-reviewed practice." },
    ],
    sidebarCta: { title: "Want feedback on your answers?", body: "A coach can review your actual answer sheets, line by line, every week.", href: "/programs#mains-mastery", label: "See the Mains Mastery Program" },
  },
  {
    slug: "staying-steady-managing-stress",
    title: "Staying Steady: Managing Stress Through a Multi-Year UPSC Journey",
    description: "Practical, honest ways to manage stress and stay motivated across the years a UPSC preparation journey typically takes.",
    category: "Wellbeing",
    readTime: "5 min read",
    body: [
      { type: "p", text: "Nobody tells first-time aspirants how long this actually takes. Somewhere between the second and third year, the initial motivation that got you started runs out." },
      { type: "h2", text: "1. Separate the exam from your self-worth" },
      { type: "p", text: "A poor mock score is information about that test, on that day. It is not a verdict on you as a person." },
      { type: "h2", text: "2. Build a routine that doesn't depend on motivation" },
      { type: "p", text: "A fixed daily routine means your preparation keeps moving even on the days you don't feel like it." },
      { type: "h2", text: "3. Talk to someone who isn't also an aspirant" },
      { type: "p", text: "Deliberately keeping at least one relationship outside that world gives you somewhere to be a whole person, not just a candidate." },
      { type: "h2", text: "4. Expect the dip — don't panic when it arrives" },
      { type: "p", text: "Almost every long-term aspirant hits a stretch where nothing feels like it's working. This is common enough to be expected." },
      { type: "h2", text: "5. Revisit your \"why\" on a schedule, not just in a crisis" },
      { type: "p", text: "A short, regular check-in — even once a month — keeps your reasons current instead of stale." },
      { type: "p", text: "If you're finding the weight of this genuinely hard to carry, that's worth talking to someone about — a coach, a counsellor, or a trusted person in your life. Preparation is demanding; it isn't meant to be carried alone." },
    ],
    sidebarCta: { title: "Coaching that looks at the whole picture", body: "Confidence and wellbeing check-ins are part of every coaching cycle here.", href: "/about", label: "See How We Coach" },
  },
  {
    slug: "daily-current-affairs-habit",
    title: "Building a Daily Current Affairs Habit You'll Actually Keep",
    description: "A realistic approach to daily current affairs for UPSC — how much to read, how to take notes, and how to link it to the static syllabus.",
    category: "Current Affairs",
    readTime: "7 min read",
    body: [
      { type: "p", text: "Current affairs never stops growing, which is why so many aspirants either over-read it or quietly give up on it. Here's a habit built to actually last." },
      { type: "h2", text: "1. Cap your daily reading time" },
      { type: "p", text: "45 to 60 minutes is plenty for a focused daily read, rather than an open-ended task that expands to fill however much time you have." },
      { type: "h2", text: "2. Read for the exam, not for general knowledge" },
      { type: "p", text: "Ask a simple filter question: could this plausibly become a Prelims option, a Mains reference point, or an essay example?" },
      { type: "h2", text: "3. Take notes in your own words, immediately" },
      { type: "p", text: "A two-line note in your own words takes longer in the moment but saves far more time at revision." },
      { type: "h2", text: "4. Link every note to a static topic" },
      { type: "p", text: "This is the step most aspirants skip, and it's the one that actually makes current affairs useful for Mains." },
      { type: "h2", text: "5. Compile monthly, don't just accumulate daily" },
      { type: "p", text: "A short monthly compilation turns a growing pile into something revisable before your exam." },
      { type: "h3", text: "The habit that survives exam pressure" },
      { type: "p", text: "Keep the daily version small, and let the monthly compilation do the heavy lifting for revision." },
    ],
    sidebarCta: { title: "See the Current Affairs Program", body: "Concise briefings and static-syllabus linkages, offered in seasonal batches.", href: "/programs#current-affairs", label: "View Program Details" },
  },
  {
    slug: "choosing-upsc-optional-subject",
    title: "How to Choose a UPSC Optional Subject Without Regretting It",
    description: "A practical framework for picking a UPSC Mains optional subject — scoring trends, overlap with GS, resource availability, and genuine interest.",
    category: "Mains",
    readTime: "9 min read",
    body: [
      { type: "p", text: "The optional subject decision gets more agonising advice than almost any other part of UPSC preparation. It's a decision you can make well with a clear framework." },
      { type: "h2", text: "1. Start with genuine interest, not just scoring trends" },
      { type: "p", text: "A subject you find genuinely interesting is one you'll actually revise, rather than avoid." },
      { type: "h2", text: "2. Check the overlap with General Studies" },
      { type: "p", text: "Subjects like Geography, Political Science and Sociology overlap meaningfully with GS, so every hour spent also strengthens your GS answers." },
      { type: "h2", text: "3. Be honest about resource availability" },
      { type: "p", text: "A subject with great scoring potential but no structured guidance available to you personally is a much harder path than the numbers suggest." },
      { type: "h2", text: "4. Talk to people who've actually taken it — recently" },
      { type: "p", text: "Trends shift. Seek out first-hand experience rather than relying on general reputation." },
      { type: "h2", text: "5. Make the decision once, and commit" },
      { type: "p", text: "Switching optionals mid-preparation is expensive. Give yourself a genuine, time-bound period to decide, then commit fully." },
      { type: "h3", text: "A quick way to check your shortlist" },
      { type: "p", text: "Rate each subject out of 5 on genuine interest, GS overlap, resource availability, and scoring consistency." },
    ],
    sidebarCta: { title: "Coaching for Geography, Polity & Psychology", body: "These three optionals are especially well covered in the Mains Mastery Program.", href: "/programs#mains-mastery", label: "See the Mains Mastery Program" },
  },
  {
    slug: "week-before-upsc-interview",
    title: "What to Actually Do in the Week Before Your UPSC Interview",
    description: "A practical, day-by-day approach to the final week before your UPSC personality test.",
    category: "Interview",
    readTime: "6 min read",
    body: [
      { type: "p", text: "The week before your interview is not the time to learn anything new — it's the time to consolidate what you already know and arrive calm." },
      { type: "h2", text: "Days 1–2: Re-read your own DAF, closely" },
      { type: "p", text: "Read it as if you were the panel — what would you ask, based on what you wrote?" },
      { type: "h2", text: "Days 3–4: Revisit current affairs from the last 2–3 months" },
      { type: "p", text: "A focused pass through the last two to three months is far more useful than a broad, shallow re-read of everything." },
      { type: "h2", text: "Day 5: One full mock, then stop analysing it" },
      { type: "p", text: "A single realistic mock panel this late calibrates your composure and pacing. Resist running several back-to-back." },
      { type: "h2", text: "Days 6–7: Deliberately do less" },
      { type: "p", text: "Light revision, good sleep, and normal daily activities do more for your composure than one more late night of cramming." },
      { type: "h3", text: "On the day itself" },
      { type: "p", text: "Answer what's asked, honestly, in your own words. A steady \"I don't know, but here's how I'd think about it\" beats a shaky guess." },
    ],
    sidebarCta: { title: "Interview Guidance, done right", body: "One-on-one DAF review and confidence coaching, built for the day itself.", href: "/programs#interview", label: "See Interview Guidance" },
  },
];

export function getPostBySlug(slug) {
  return posts.find((p) => p.slug === slug);
}
